name: TVBoxOS-Mobile CI/CD

on:
  push:
    branches: [ main, master, material-design-3-update ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  # 允许手动触发工作流
  workflow_dispatch:
    inputs:
      build_type:
        description: '构建类型 (debug/release)'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release
      create_release:
        description: '创建GitHub Release'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set build version
        id: set_version
        run: |
          VERSION_NAME=$(grep 'versionName' app/build.gradle | awk '{print $2}' | tr -d "'")
          VERSION_CODE=$(grep 'versionCode' app/build.gradle | awk '{print $2}')
          BUILD_DATE=$(date +'%Y%m%d')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "APK_NAME=XMBOX_v${VERSION_NAME}_${BUILD_DATE}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        if: ${{ github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == '' }}
        run: ./gradlew assembleDebug --stacktrace

      - name: Build Release APK
        if: ${{ github.event.inputs.build_type == 'release' || github.ref_type == 'tag' }}
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign Release APK
        if: ${{ github.event.inputs.build_type == 'release' || github.ref_type == 'tag' }}
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Rename signed APK
        if: ${{ github.event.inputs.build_type == 'release' || github.ref_type == 'tag' }}
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/${{ env.APK_NAME }}.apk

      - name: Upload Debug APK
        if: ${{ github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == '' }}
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        if: ${{ github.event.inputs.build_type == 'release' || github.ref_type == 'tag' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/release/${{ env.APK_NAME }}.apk

      - name: Create GitHub Release
        if: ${{ (github.event.inputs.create_release == 'true' || github.ref_type == 'tag') && (github.event.inputs.build_type == 'release' || github.ref_type == 'tag') }}
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/${{ env.APK_NAME }}.apk
          name: TVBoxOS-Mobile v${{ env.VERSION_NAME }}
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('v{0}', env.VERSION_NAME) }}
          body: |
            ## TVBoxOS-Mobile v${{ env.VERSION_NAME }} (${{ env.BUILD_DATE }})

            ### 更新内容
            - Material Design 3 主题更新
            - UI组件优化
            - 功能改进

            ### 下载
            - [MBox_v${{ env.VERSION_NAME }}_${{ env.BUILD_DATE }}.apk](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_type == 'tag' && github.ref_name || format('v{0}', env.VERSION_NAME) }}/MBox_v${{ env.VERSION_NAME }}_${{ env.BUILD_DATE }}.apk)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
