name: Resource Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  check-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check resource file names
        run: |
          echo "Checking for invalid resource file names..."
          
          # 查找所有资源文件
          find app/src/main/res -type f | while read file; do
            # 获取文件名（不包含路径）
            filename=$(basename "$file")
            
            # 检查文件名是否包含非法字符（只允许小写字母、数字和下划线）
            if [[ ! $filename =~ ^[a-z0-9_\.]+$ ]]; then
              echo "Warning: Invalid resource file name: $file"
              
              # 生成新的文件名（将非法字符替换为下划线）
              newfilename=$(echo "$filename" | sed -E 's/[^a-z0-9_\.]/_/g')
              newfile=$(dirname "$file")/"$newfilename"
              
              echo "  Suggested new name: $newfile"
              
              # 如果您想自动重命名文件，取消下面这行的注释
              # git mv "$file" "$newfile"
            fi
          done
          
          # 如果您启用了自动重命名，可以添加以下代码来提交更改
          # if [[ -n $(git status -s) ]]; then
          #   git config --global user.name "GitHub Actions Bot"
          #   git config --global user.email "actions@github.com"
          #   git add .
          #   git commit -m "Fix invalid resource file names"
          #   git push
          # fi
